name: Public Jax CI
on:
  workflow_dispatch:
    inputs:
      jax_commit:
        description: 'Specify the commit hash'
        default: 'master'

jobs:
  JAX-CI:
    runs-on: Intel_openxla
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      # Rest of your workflow steps...
